# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cmdhistory.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from yamcs.protobuf import yamcs_pb2 as yamcs_dot_protobuf_dot_yamcs__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cmdhistory.proto',
  package='',
  syntax='proto2',
  serialized_options=b'\n\035org.yamcs.cmdhistory.protobuf',
  serialized_pb=b'\n\x10\x63mdhistory.proto\x1a\x1ayamcs/protobuf/yamcs.proto\"1\n\x0e\x41ssignmentInfo\x12\x1f\n\nassignment\x18\x01 \x03(\x0b\x32\x0b.Assignment\"S\n\nAssignment\x12\x0c\n\x04name\x18\x01 \x01(\t\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.yamcs.protobuf.Value\x12\x11\n\tuserInput\x18\x03 \x01(\x08\x42\x1f\n\x1dorg.yamcs.cmdhistory.protobuf'
  ,
  dependencies=[yamcs_dot_protobuf_dot_yamcs__pb2.DESCRIPTOR,])




_ASSIGNMENTINFO = _descriptor.Descriptor(
  name='AssignmentInfo',
  full_name='AssignmentInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='assignment', full_name='AssignmentInfo.assignment', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=97,
)


_ASSIGNMENT = _descriptor.Descriptor(
  name='Assignment',
  full_name='Assignment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Assignment.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Assignment.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userInput', full_name='Assignment.userInput', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=182,
)

_ASSIGNMENTINFO.fields_by_name['assignment'].message_type = _ASSIGNMENT
_ASSIGNMENT.fields_by_name['value'].message_type = yamcs_dot_protobuf_dot_yamcs__pb2._VALUE
DESCRIPTOR.message_types_by_name['AssignmentInfo'] = _ASSIGNMENTINFO
DESCRIPTOR.message_types_by_name['Assignment'] = _ASSIGNMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AssignmentInfo = _reflection.GeneratedProtocolMessageType('AssignmentInfo', (_message.Message,), {
  'DESCRIPTOR' : _ASSIGNMENTINFO,
  '__module__' : 'cmdhistory_pb2'
  # @@protoc_insertion_point(class_scope:AssignmentInfo)
  })
_sym_db.RegisterMessage(AssignmentInfo)

Assignment = _reflection.GeneratedProtocolMessageType('Assignment', (_message.Message,), {
  'DESCRIPTOR' : _ASSIGNMENT,
  '__module__' : 'cmdhistory_pb2'
  # @@protoc_insertion_point(class_scope:Assignment)
  })
_sym_db.RegisterMessage(Assignment)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
