# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timeline.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='timeline.proto',
  package='',
  syntax='proto2',
  serialized_options=b'\n\033org.yamcs.timeline.protobufB\rTimelineProtoP\001',
  serialized_pb=b'\n\x0etimeline.proto\"\xa1\x01\n\nBandFilter\x12\'\n\x07\x66ilters\x18\x01 \x03(\x0b\x32\x16.BandFilter.ItemFilter\x1a-\n\x0f\x46ilterCriterion\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x1a;\n\nItemFilter\x12-\n\x08\x63riteria\x18\x01 \x03(\x0b\x32\x1b.BandFilter.FilterCriterionB.\n\x1borg.yamcs.timeline.protobufB\rTimelineProtoP\x01'
)




_BANDFILTER_FILTERCRITERION = _descriptor.Descriptor(
  name='FilterCriterion',
  full_name='BandFilter.FilterCriterion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='BandFilter.FilterCriterion.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='BandFilter.FilterCriterion.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=119,
)

_BANDFILTER_ITEMFILTER = _descriptor.Descriptor(
  name='ItemFilter',
  full_name='BandFilter.ItemFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='criteria', full_name='BandFilter.ItemFilter.criteria', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=180,
)

_BANDFILTER = _descriptor.Descriptor(
  name='BandFilter',
  full_name='BandFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filters', full_name='BandFilter.filters', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_BANDFILTER_FILTERCRITERION, _BANDFILTER_ITEMFILTER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=180,
)

_BANDFILTER_FILTERCRITERION.containing_type = _BANDFILTER
_BANDFILTER_ITEMFILTER.fields_by_name['criteria'].message_type = _BANDFILTER_FILTERCRITERION
_BANDFILTER_ITEMFILTER.containing_type = _BANDFILTER
_BANDFILTER.fields_by_name['filters'].message_type = _BANDFILTER_ITEMFILTER
DESCRIPTOR.message_types_by_name['BandFilter'] = _BANDFILTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BandFilter = _reflection.GeneratedProtocolMessageType('BandFilter', (_message.Message,), {

  'FilterCriterion' : _reflection.GeneratedProtocolMessageType('FilterCriterion', (_message.Message,), {
    'DESCRIPTOR' : _BANDFILTER_FILTERCRITERION,
    '__module__' : 'timeline_pb2'
    # @@protoc_insertion_point(class_scope:BandFilter.FilterCriterion)
    })
  ,

  'ItemFilter' : _reflection.GeneratedProtocolMessageType('ItemFilter', (_message.Message,), {
    'DESCRIPTOR' : _BANDFILTER_ITEMFILTER,
    '__module__' : 'timeline_pb2'
    # @@protoc_insertion_point(class_scope:BandFilter.ItemFilter)
    })
  ,
  'DESCRIPTOR' : _BANDFILTER,
  '__module__' : 'timeline_pb2'
  # @@protoc_insertion_point(class_scope:BandFilter)
  })
_sym_db.RegisterMessage(BandFilter)
_sym_db.RegisterMessage(BandFilter.FilterCriterion)
_sym_db.RegisterMessage(BandFilter.ItemFilter)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
