name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install flake8
      - name: Lint with flake8
        run: flake8 src --exclude '*pb2.py' --count --show-source --statistics

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Set up sphinx
        run: |
          cd docs
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set up yamcs-cli
        run: pip install .
      - name: Generate docs
        run: |
          cd docs
          make man html
